services:
  krakenSql:
    container_name: krakenSql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1cc2c364-fd64-42ef-8178-1b2c94410fc8
      MYSQL_DATABASE: kraken
      MYSQL_USER: kraken
      MYSQL_PASSWORD: kraken
    ports:
      - '3306:3306'
  krakenSrv:
    container_name: krakenSrv
    image: nginx:alpine
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ./nginx:/etc/nginx
      - /mnt/Kraken/Assets:/media/Assets:ro