version: '3.1'

services:
  krakenSql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1cc2c364-fd64-42ef-8178-1b2c94410fc8
      MYSQL_DATABASE: kraken
      MYSQL_USER: kraken
      MYSQL_PASSWORD: kraken
    ports:
      - '3306:3306'