hostname = "kraken.local"
username = "kraken"
password = "kraken"
database = "kraken"

b_path = "public/Assets/"
m_path = b_path + "Movies"
s_path = b_path + "Series"
i_path = b_path + "Images"
b_url = "/Assets/"
json_fold = b_path + "JSON_DMPS/"